name: Deploy Docker Stack

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: deploy-main
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker compose up
        shell: cmd
        run: |
          "C:\Program Files\Docker\Docker\resources\bin\docker.exe" compose --project-name physioconnect-marketplace-application7 up -d --build

      - name: Show running containers
        shell: cmd
        run: |
          "C:\Program Files\Docker\Docker\resources\bin\docker.exe" compose --project-name physioconnect-marketplace-application7 ps